
debug: false

#spring:
#  profiles:
#    active: @spring.profiles.active@



logging:
  path: .
  file: ${logging.path}/react.log
  level:
    root: info
    com:
      softvision:
        example:
          springboot: debug
#    org.springframework.cloud.consul.discovery: trace
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG
        catalina:
          valves:
            RemoteIpValve: DEBUG
        tomcat:
          util:
            http:
              Rfc6265CookieProcessor: DEBUG


server:
  port : ${PORT:8180}
  use-forward-headers: true  # allows handling of nginx reverse proxy


spring:
  cloud:
    consul:
      binder:
        enabled: ${CONSUL_ENABLE:false}
      discovery:
        health-check-interval: 30s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${localhost-name:${random.value}}
        tags: management.context-path=actuator, health.path=/health
        management-tags: management.context-path=actuator, health.path=/actuator/health
        fail-fast: false
        enabled: true
      config:
        enabled: false
      enabled: ${CONSUL_ENABLE:false}
    bus:
      enabled: false
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

  sleuth:
    sampler:
      probability: 1.0
    web:
      additional-skip-pattern: ".*/actuator.*"
  zipkin:
    base-url: http://${ZIPKIN_HOST:zipkin}/
    service:
      name: ${spring.application.name}
    discovery-client-enabled: true

management:
  endpoints:
    web:
      cors:  # CORS SETUP
        allowed-origins: ${ALLOW_ORIGINS:"http://serverapi ,http://localhost:9000"}
        allowed-methods: ${ALLOWED_METHODS:"GET, POST, PUT, DELETE"}
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

