
debug: false

#spring:
#  profiles:
#    active: @spring.profiles.active@



logging:
  path: .
  file: ${logging.path}/react.log
  level:
    root: info
    com:
      softvision:
        example:
          springboot: debug

server:
  port : 8180


management:
  endpoints:
    web:
      cors:  # CORS SETUP
        allowed-origins: ${ALLOW_ORIGINS:"http://serverapi ,http://localhost:9000"}
        allowed-methods: ${ALLOWED_METHODS:"GET, POST, PUT, DELETE"}
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

